// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: proto/expenses.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateExpenseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunks        []byte                 `protobuf:"bytes,1,opt,name=chunks,proto3" json:"chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExpenseRequest) Reset() {
	*x = CreateExpenseRequest{}
	mi := &file_proto_expenses_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExpenseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExpenseRequest) ProtoMessage() {}

func (x *CreateExpenseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expenses_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExpenseRequest.ProtoReflect.Descriptor instead.
func (*CreateExpenseRequest) Descriptor() ([]byte, []int) {
	return file_proto_expenses_proto_rawDescGZIP(), []int{0}
}

func (x *CreateExpenseRequest) GetChunks() []byte {
	if x != nil {
		return x.Chunks
	}
	return nil
}

type CreateExpenseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExpenseResponse) Reset() {
	*x = CreateExpenseResponse{}
	mi := &file_proto_expenses_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExpenseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExpenseResponse) ProtoMessage() {}

func (x *CreateExpenseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expenses_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExpenseResponse.ProtoReflect.Descriptor instead.
func (*CreateExpenseResponse) Descriptor() ([]byte, []int) {
	return file_proto_expenses_proto_rawDescGZIP(), []int{1}
}

func (x *CreateExpenseResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetHeatMapDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHeatMapDataRequest) Reset() {
	*x = GetHeatMapDataRequest{}
	mi := &file_proto_expenses_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHeatMapDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHeatMapDataRequest) ProtoMessage() {}

func (x *GetHeatMapDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expenses_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHeatMapDataRequest.ProtoReflect.Descriptor instead.
func (*GetHeatMapDataRequest) Descriptor() ([]byte, []int) {
	return file_proto_expenses_proto_rawDescGZIP(), []int{2}
}

func (x *GetHeatMapDataRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetHeatMapDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HeatMapData   []*HeatMapData         `protobuf:"bytes,1,rep,name=heat_map_data,json=heatMapData,proto3" json:"heat_map_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHeatMapDataResponse) Reset() {
	*x = GetHeatMapDataResponse{}
	mi := &file_proto_expenses_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHeatMapDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHeatMapDataResponse) ProtoMessage() {}

func (x *GetHeatMapDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expenses_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHeatMapDataResponse.ProtoReflect.Descriptor instead.
func (*GetHeatMapDataResponse) Descriptor() ([]byte, []int) {
	return file_proto_expenses_proto_rawDescGZIP(), []int{3}
}

func (x *GetHeatMapDataResponse) GetHeatMapData() []*HeatMapData {
	if x != nil {
		return x.HeatMapData
	}
	return nil
}

type HeatMapData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Day           string                 `protobuf:"bytes,1,opt,name=day,proto3" json:"day,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeatMapData) Reset() {
	*x = HeatMapData{}
	mi := &file_proto_expenses_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeatMapData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeatMapData) ProtoMessage() {}

func (x *HeatMapData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expenses_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeatMapData.ProtoReflect.Descriptor instead.
func (*HeatMapData) Descriptor() ([]byte, []int) {
	return file_proto_expenses_proto_rawDescGZIP(), []int{4}
}

func (x *HeatMapData) GetDay() string {
	if x != nil {
		return x.Day
	}
	return ""
}

func (x *HeatMapData) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *HeatMapData) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type GetSpendingTypesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSpendingTypesRequest) Reset() {
	*x = GetSpendingTypesRequest{}
	mi := &file_proto_expenses_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSpendingTypesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpendingTypesRequest) ProtoMessage() {}

func (x *GetSpendingTypesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expenses_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpendingTypesRequest.ProtoReflect.Descriptor instead.
func (*GetSpendingTypesRequest) Descriptor() ([]byte, []int) {
	return file_proto_expenses_proto_rawDescGZIP(), []int{5}
}

func (x *GetSpendingTypesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type SpendingType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Spent         float64                `protobuf:"fixed64,2,opt,name=spent,proto3" json:"spent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpendingType) Reset() {
	*x = SpendingType{}
	mi := &file_proto_expenses_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpendingType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpendingType) ProtoMessage() {}

func (x *SpendingType) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expenses_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpendingType.ProtoReflect.Descriptor instead.
func (*SpendingType) Descriptor() ([]byte, []int) {
	return file_proto_expenses_proto_rawDescGZIP(), []int{6}
}

func (x *SpendingType) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SpendingType) GetSpent() float64 {
	if x != nil {
		return x.Spent
	}
	return 0
}

type GetSpendingTypesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpendingTypes []*SpendingType        `protobuf:"bytes,1,rep,name=spending_types,json=spendingTypes,proto3" json:"spending_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSpendingTypesResponse) Reset() {
	*x = GetSpendingTypesResponse{}
	mi := &file_proto_expenses_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSpendingTypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpendingTypesResponse) ProtoMessage() {}

func (x *GetSpendingTypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expenses_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpendingTypesResponse.ProtoReflect.Descriptor instead.
func (*GetSpendingTypesResponse) Descriptor() ([]byte, []int) {
	return file_proto_expenses_proto_rawDescGZIP(), []int{7}
}

func (x *GetSpendingTypesResponse) GetSpendingTypes() []*SpendingType {
	if x != nil {
		return x.SpendingTypes
	}
	return nil
}

var File_proto_expenses_proto protoreflect.FileDescriptor

const file_proto_expenses_proto_rawDesc = "" +
	"\n" +
	"\x14proto/expenses.proto\".\n" +
	"\x14CreateExpenseRequest\x12\x16\n" +
	"\x06chunks\x18\x01 \x01(\fR\x06chunks\"/\n" +
	"\x15CreateExpenseResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"0\n" +
	"\x15GetHeatMapDataRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"J\n" +
	"\x16GetHeatMapDataResponse\x120\n" +
	"\rheat_map_data\x18\x01 \x03(\v2\f.HeatMapDataR\vheatMapData\"S\n" +
	"\vHeatMapData\x12\x10\n" +
	"\x03day\x18\x01 \x01(\tR\x03day\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\"2\n" +
	"\x17GetSpendingTypesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"8\n" +
	"\fSpendingType\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05spent\x18\x02 \x01(\x01R\x05spent\"P\n" +
	"\x18GetSpendingTypesResponse\x124\n" +
	"\x0espending_types\x18\x01 \x03(\v2\r.SpendingTypeR\rspendingTypes2\xdf\x01\n" +
	"\x0fExpensesService\x12@\n" +
	"\rCreateExpense\x12\x15.CreateExpenseRequest\x1a\x16.CreateExpenseResponse(\x01\x12A\n" +
	"\x0eGetHeatMapData\x12\x16.GetHeatMapDataRequest\x1a\x17.GetHeatMapDataResponse\x12G\n" +
	"\x10GetSpendingTypes\x12\x18.GetSpendingTypesRequest\x1a\x19.GetSpendingTypesResponseB+Z)github.com/barathsurya2004/expenses/protob\x06proto3"

var (
	file_proto_expenses_proto_rawDescOnce sync.Once
	file_proto_expenses_proto_rawDescData []byte
)

func file_proto_expenses_proto_rawDescGZIP() []byte {
	file_proto_expenses_proto_rawDescOnce.Do(func() {
		file_proto_expenses_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_expenses_proto_rawDesc), len(file_proto_expenses_proto_rawDesc)))
	})
	return file_proto_expenses_proto_rawDescData
}

var file_proto_expenses_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_expenses_proto_goTypes = []any{
	(*CreateExpenseRequest)(nil),     // 0: CreateExpenseRequest
	(*CreateExpenseResponse)(nil),    // 1: CreateExpenseResponse
	(*GetHeatMapDataRequest)(nil),    // 2: GetHeatMapDataRequest
	(*GetHeatMapDataResponse)(nil),   // 3: GetHeatMapDataResponse
	(*HeatMapData)(nil),              // 4: HeatMapData
	(*GetSpendingTypesRequest)(nil),  // 5: GetSpendingTypesRequest
	(*SpendingType)(nil),             // 6: SpendingType
	(*GetSpendingTypesResponse)(nil), // 7: GetSpendingTypesResponse
}
var file_proto_expenses_proto_depIdxs = []int32{
	4, // 0: GetHeatMapDataResponse.heat_map_data:type_name -> HeatMapData
	6, // 1: GetSpendingTypesResponse.spending_types:type_name -> SpendingType
	0, // 2: ExpensesService.CreateExpense:input_type -> CreateExpenseRequest
	2, // 3: ExpensesService.GetHeatMapData:input_type -> GetHeatMapDataRequest
	5, // 4: ExpensesService.GetSpendingTypes:input_type -> GetSpendingTypesRequest
	1, // 5: ExpensesService.CreateExpense:output_type -> CreateExpenseResponse
	3, // 6: ExpensesService.GetHeatMapData:output_type -> GetHeatMapDataResponse
	7, // 7: ExpensesService.GetSpendingTypes:output_type -> GetSpendingTypesResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_expenses_proto_init() }
func file_proto_expenses_proto_init() {
	if File_proto_expenses_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_expenses_proto_rawDesc), len(file_proto_expenses_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_expenses_proto_goTypes,
		DependencyIndexes: file_proto_expenses_proto_depIdxs,
		MessageInfos:      file_proto_expenses_proto_msgTypes,
	}.Build()
	File_proto_expenses_proto = out.File
	file_proto_expenses_proto_goTypes = nil
	file_proto_expenses_proto_depIdxs = nil
}
